language: ruby
rvm:
- 2.4.1
script: "./script/cibuild"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts: $SLabServer
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
before_deploy:
  - echo -e "Host $SLabServer \n    StrictHostKeyChecking no" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_0294c1731973_key -iv $encrypted_0294c1731973_iv
    -in .travis_deploy_rsa.enc -out /tmp/deployed_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deployed_rsa
  - ssh-add /tmp/deployed_rsa 
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avz --delete-after ./_site $SLabUser@$SLabServer:$SLabPath/
  on:
    branch: master
